---
- hosts: all
  remote_user: root
  tasks:
  - name: delete /opt/test.log
    shell: rm -rf /opt/test.log
  tasks:
  - name: show /
    shell: ls /
- hosts: webservers
  remote_user: root
  tasks:
  - name: test
    shell: echo "test">/test.log
